/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _IMUData {
    uint64_t count;
    float acc_x;
    float acc_y;
    float acc_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
} IMUData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define IMUData_init_default                     {0, 0, 0, 0, 0, 0, 0}
#define IMUData_init_zero                        {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define IMUData_count_tag                        1
#define IMUData_acc_x_tag                        2
#define IMUData_acc_y_tag                        3
#define IMUData_acc_z_tag                        4
#define IMUData_gyro_x_tag                       5
#define IMUData_gyro_y_tag                       6
#define IMUData_gyro_z_tag                       7

/* Struct field encoding specification for nanopb */
#define IMUData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   count,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_x,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_y,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_z,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,            7)
#define IMUData_CALLBACK NULL
#define IMUData_DEFAULT NULL

extern const pb_msgdesc_t IMUData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define IMUData_fields &IMUData_msg

/* Maximum encoded size of messages (where known) */
#define IMUData_size                             41
#define MESSAGES_PB_H_MAX_SIZE                   IMUData_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
