site_name: PicoQuake

repo_url: https://github.com/mrmp17/PicoQuake
repo_name: mrmp17/PicoQuake

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: orange

copyright: Copyright &copy; 2024 PLab