site_name: PicoQuake

repo_url: https://github.com/PLab-SI/PicoQuake
repo_name: PLab-SI/PicoQuake

nav:
  - Home: index.md
  - Example Use Cases:
    - examples/trackpad.md
    - examples/bldc.md
  - installation.md
  - usage.md
  - plotting.md
  - cli.md
  - Python API:
    - Examples: python_api/examples.md
    - Reference:
      - python_api/interface.md
      - python_api/data.md
      - python_api/exceptions.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: orange

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            docstring_section_style: list

markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
  - toc:
      permalink: true

copyright: Copyright &copy; 2024 PLab