/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IMUData, IMUData, AUTO)


PB_BIND(IMUDataSmol, IMUDataSmol, AUTO)


PB_BIND(Status, Status, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(Command, Command, AUTO)



